#!/bin/sh
#
# lxc-goodies
# Copyright © 2010 Mikhail Gusarov <dottedmag@dottedmag.net>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51 Franklin
# Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

set -e

#
# Creates new debian instance, fixes LXC-incompatible stuff, installs SSH
# server, provides public SSH key and sets up networking and Zeroconf.
#
# Usage:
#
#  user@host $ sudo lxc-goodies-mkdebian vm1 sid
#  ...
#  user@host $ sudo lxc-start -n vm1 -d
#  user@host $ ssh root@vm1.local
#  ...
#  root@vm1 #
#

PATH=$PATH:/usr/share/lxc-goodies
. lxc-goodies-config

if [ $# -lt 1 -o $# -gt 3 ]; then
   echo "Usage: $0 <name> [<distribution>]"
   exit 1
fi

if [ ! -f /usr/sbin/debootstrap ]; then
    echo "Please install debootstrap first."
    exit 1
fi

NAME="$1"
if [ "x$2" = x ]; then
    DISTRO=sid
else
    DISTRO="$2"
fi

LXC_ROOT=/var/lib/lxc

if [ -e "$LXC_ROOT/$1" ]; then
    echo "$1 already exists."
    exit 1
fi

ROOTFS=$LXC_ROOT/$1/rootfs

mkdir -p "$LXC_ROOT/$1"

cat <<EOF > "$LXC_ROOT/$1/config"
lxc.utsname=$1

lxc.network.type=veth
lxc.network.flags=up
lxc.network.link=$BRIDGE_IFACE

lxc.pts=256
lxc.tty=4

lxc.rootfs=$ROOTFS
EOF

debootstrap --include openssh-server,avahi-daemon --exclude udev $DISTRO $ROOTFS $DEBIAN_MIRROR

echo $NAME > $ROOTFS/etc/hostname

cat <<EOF > $ROOTFS/etc/network/interfaces
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp
EOF

sed -i -e 's/^root:\*:/root::/' $ROOTFS/etc/shadow

touch $ROOTFS/root/.hushlogin

mkdir -m 700 $ROOTFS/root/.ssh

#
# FIXME: hardcoded
#
echo "$ROOT_SSH_KEY" > $ROOTFS/root/.ssh/authorized_keys
chmod 600 $ROOTFS/root/.ssh/authorized_keys
