#!/bin/sh
#
# lxc-goodies
# Copyright © 2010 Mikhail Gusarov <dottedmag@dottedmag.net>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51 Franklin
# Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

PATH=$PATH:/usr/share/lxc-goodies
. lxc-goodies-config

if ! grep -q $CGROUP_LOCATION /etc/fstab; then
    cat <<EOF >> /etc/fstab
cgroup $CGROUP_LOCATION cgroup defaults 0 0
EOF
    mount $CGROUP_LOCATION
fi
